spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://${DB_HOST:192.168.50.108}:${DB_PORT:3306}/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=TRUE
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123}

    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000

  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true

mybatis:
  type-aliases-package: com.throne.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
